# LingsHTTPUtils 配置文件
#
# 每个模块名字随意
#
# mode
# json 获取json格式的字符串并解析
# string 直接获取文本
#
# key 当模式为json时要获取的值对应的键
# 只在模式为json时可用
#
# apiname 比如你想要PAPI变量名为 %lhu_ab_cd% 那么apiname为"ab_cd"
# 此插件的变量名头为lhu
#
# url 要请求的网页链接
#
# reqTime 请求超时时间(ms)
# 仅当reqMode: Cycle时可用
#
# refInterval 请求间隔时间
#
# method 请求方法 不指定则使用GET
#
# reqMode 请求方式
# Cycle 循环请求
# inTime 即时请求(注意可能卡住服务器)
bilibili_followers:
  apiname: "bilibili_followers"
  url: "https://api.bilibili.com/x/relation/stat?vmid=359206390"
  mode: "json"
  method: "GET"
  key: "data.follower"
  reqTime: 10000
  reqMode: "Cycle"
  refInterval: 30000
hitokoto:
  apiname: "hitokoto"
  url: "https://v1.hitokoto.cn/"
  mode: "json"
  method: "GET"
  key: "hitokoto"
  reqTime: 10000
  reqMode: "Cycle"
  refInterval: 15000
