name: LingsHttpUtils
version: '${project.version}'
main: cn.lingsmc.lingshttputils.LingsHttpUtils
depend: [ PlaceholderAPI ]
authors: [ Crsuh2er0 ]
description: 从http接口获取数据到PAPI

commands:
  lingshttputils:
    description: LingsHttpUtils插件指令
    aliases:
      - lhu
    usage: |
      /lhu help
permissions:
  lingshttputils.admin:
    description: LingsHttpUtils插件管理权限
    default: op
