name: LingsHttpUtils
version: '${project.version}'
main: cn.lingsmc.lingshttputils.LingsHTTPUtils
depend: [ PlaceholderAPI ]
authors: [ Crsuh2er0 ]
description: Connect website text with PAPI.

commands:
  lingshttputils:
    description: LingsHttpUtils插件指令
    aliases:
      - lhu
    usage: |
      /lhu help
permissions:
  lingshttputils.admin:
    description: LingsHttpUtils插件管理权限